### ISSUE TITLE
TypeScript type declarations

### ISSUE THREAD

**Issue by BonneVoyager** [mdtanrikulu/use-metamask#15]
Hi there, do you have any plans on adding TypeScript type declarations? There is no `@types/use-metamask` package yet, so many developers will face this issue:
![Screenshot 2021-08-12 at 10 37 15](https://user-images.githubusercontent.com/8746962/129165944-493f747d-9a6a-4273-b29d-91c5c65b56fd.png)

**Comment by mdtanrikulu** [comment]
Hi! that's a good point. I will definitely do as soon as possible.

**Comment by mdtanrikulu** [comment]
Just published the new version, it should work just fine with ts projects now!
