### ISSUE TITLE
Would it be possible to build a version without Context and simply useState instead?

### ISSUE THREAD

**Issue by hems** [mdtanrikulu/use-metamask#17]
Hello, first of all, thanks a lot for your work on this library.

Secondly, I'm wondering if it wouldn't be possible to instead use only `useState` inside of the hook or change the hook implementation in order to remove the "wrap your app in this context" requirement...

I find that requiring a user to wrap the application in a "context/state component" can start clogging the overall app.

✌️

**Comment by mdtanrikulu** [comment]
Hi thank you for your nice words! I would love to see more technical information about clogging part. Context component should not cause any clogging unless you call `useContext` hook on main app without any memoization strategy.

**Comment by hems** [comment]
> Hi thank you for your nice words! I would love to see more technical information about clogging part. Context component should not cause any clogging unless you call `useContext` hook on main app without any memoization strategy.

sorry i think "clogging" isn't the right word, but what i meant is that i have to wrap the app with a `MetamaskStateProvider` tag so if i would use let's say 10-15 hooks similar to this on my app, my app tree would end up being wrapped by 15 providers...

considering all the MetaMask information is a "singleton" ( i.e. unique state globally available state on the window ) i wonder why can't we just wrap all the logic on the hook itself and avoid having to wrap the app in a `Provider` tag... ?

Does that make sense?

**Comment by karcreativeworks** [comment]
Maybe this will help you -> https://github.com/TheMoonDevs/DApp-Reacthooks.

Remember these are just snippets, and you should copy/paste and edit them to fit your needs.

**Comment by hems** [comment]
> Maybe this will help you -> https://github.com/TheMoonDevs/DApp-Reacthooks.
> 
> Remember these are just snippets, and you should copy/paste and edit them to fit your needs.

interesting, this indeed works in a similar way to what i envisioned.. the hooks are self contained and don't require a context wrapper.

i'll let you know if i end up modifying coming up with something different.
