### ISSUE TITLE
Missing dependency when build with vite

### ISSUE THREAD

**Issue by nicolasdanelon** [mdtanrikulu/use-metamask#28]
I'm building a website with the latest version of vite@2.9.12 and preact@10.8.1. 

I'm seeing the following error:
<img width="664" alt="Uncaught ReferenceError: regeneratorRuntime is not defined
" src="https://user-images.githubusercontent.com/2846046/174722832-ba5fbf9e-080a-4bd2-9302-4110ba5ec9da.png">

this is the line 93:
<img width="765" alt="Uncaught ReferenceError: regeneratorRuntime is not defined - regeneratorRuntime.mark(function _callee(Web3Interface)" src="https://user-images.githubusercontent.com/2846046/174722979-5c377e44-d684-4162-8986-7939853a400c.png">

after a little bit of googling I saw that create-react-app has somewhere this package: [regenerator runtime](https://www.npmjs.com/package/regenerator-runtime) since I'm not using creat-react-app I don't have that package.

I don't know why, but on Firefox sometimes the website works... and sometimes it doesn't. 

All my code works fine if I try create-react-app, but with vite it does not. I can create a stackblitz if you please, just let me know.

I fix this bug adding regenerator runtime to my website. even if I'm not using it I just import it on my entry point and eventing works fine.

Cheers! 🍻

**Comment by mdtanrikulu** [comment]
Hi, the only solution right now is adding runtime-generator dependency either in this library or in the project using vite. I would like to solve the problem in library side but, the library is not only used with vite projects but others as well, so this dependency will put additional fatty kb's for the other projects if I do it. I think the best approach is the vite project owner to handle the issue on their project.
