### ISSUE TITLE
update isConnected silently

### ISSUE THREAD

**Issue by z384647062** [mdtanrikulu/use-metamask#8]
> Note: If you would like to check **if Metamask is whether already connected to your dapp or not** , you can call getAccounts method beforehand.

Calling `getAccounts` will still popup the plugin window of Metamask.
Is it possible to update the connecting status( isConnected ) silently as `isConnected` won't be updated automatically after refreshing the page.

**Comment by mdtanrikulu** [comment]
Thank you! It's a good idea. But I am not sure If I can query Metamask without the extension popping up. When metamask is already connected, everything is fine but the otherwise the only way of getting this information is querying and querying will trigger the extension popup. 

I would love to keep this issue open until finding if there is a way to do or not.

**Comment by z384647062** [comment]
I looked up another project **VGLoic/metamask-react** , method `eth_accounts` may works.
```typescript
async function synchronize(dispatch: (action: Action) => void) {
  const ethereum = (window as WindowInstanceWithEthereum).ethereum;
  const isMetaMaskAvailable = Boolean(ethereum) && ethereum.isMetaMask;
  if (!isMetaMaskAvailable) {
    dispatch({ type: "metaMaskUnavailable" });
    return;
  }

  const chainId: string = await ethereum.request({
    method: "eth_chainId",
  });

  const isUnlocked = await ethereum._metamask.isUnlocked();

  if (!isUnlocked) {
    dispatch({ type: "metaMaskLocked", payload: { chainId } });
    return;
  }

  // use eth_accounts instead of eth_requestAccounts.
  const accessibleAccounts: string[] = await ethereum.request({
    method: "eth_accounts",
  });

  if (accessibleAccounts.length === 0) {
    dispatch({ type: "metaMaskUnlocked", payload: { chainId } });
  } else {
    dispatch({
      type: "metaMaskConnected",
      payload: { accounts: accessibleAccounts, chainId },
    });
  }
}
```

**Comment by mdtanrikulu** [comment]
Yes,  I can confirm it works as intended. More detailed information about it is [here](https://docs.metamask.io/guide/rpc-api.html?#permissions).

Thanks for sharing with me @z384647062! I will implement it quite soon and ping here when it is ready.

**Comment by mdtanrikulu** [comment]
It's out! Now you are able use silent getAccounts method with v1.2.2. Thanks for your contribution!
